services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
        VITE_BACKEND_SOCKET_URL: ${VITE_BACKEND_SOCKET_URL}
        VITE_PWD_SIGNUP_ENABLED: true
        VITE_GA_TRACKING_ID: ""
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_LOG_LEVEL=0
    command: >
      mongod
      --quiet
      --setParameter diagnosticDataCollectionEnabled=false
      --setParameter logComponentVerbosity={}
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge